### ISSUE TITLE
Link to VM is incorrect

### ISSUE THREAD

**Issue by jmaassen** [NLeSC/xenon-rse2017-tutorial#19]
The link to the VM in readthedocs.io seems to point to the empty VM image, not the filled one. It should point to: 

https://drive.google.com/open?id=0B1GaxSkd5lU8UkF6V1A1VGpPZ2c

but it points to: 

https://drive.google.com/file/d/0B1GaxSkd5lU8MTFxN3JLaHlXT2s/view

**Comment by jspaaks** [comment]
Updated.
