### ISSUE TITLE
add howto ssh into vm

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/xenon-rse2017-tutorial#5]
see jason's email

**Comment by jspaaks** [comment]
fixed in https://github.com/NLeSC/xenon-rse2017-tutorial/tree/262a30eeebe93d28ab2b940a43999ebeb75b1b01

**Comment by sverhoeven** [comment]
On [step 3](https://github.com/NLeSC/xenon-rse2017-tutorial/blob/262a30eeebe93d28ab2b940a43999ebeb75b1b01/ssh-into-vm.md) you are missing a `sudo`.

**Comment by jspaaks** [comment]
fixed, closing
